# -*- coding: utf-8 -*-
"""DPChenhuanJi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKO84dfT16jjcl1_tUDM_9F6W1wUgveC
"""

import pandas as pd
import numpy as np

# ===== 1. Load the raw data =====
df = pd.read_csv("steamcharts.csv")
print("Raw data shape:", df.shape)
print(df.head())

# ===== 2. Parse the month variable =====
# The original format is like "Sep-25" (abbreviated month + two-digit year)
# %b = abbreviated month name (e.g., Jan, Feb, Mar)
# %y = two-digit year
df["month_parsed"] = pd.to_datetime(df["month"], format="%b-%y", errors="coerce")

# Drop rows where month parsing failed
df = df.dropna(subset=["month_parsed"])

# Sort by game and time
df = df.sort_values(["steam_appid", "month_parsed"]).reset_index(drop=True)

print("Earliest month:", df["month_parsed"].min())
print("Latest month:", df["month_parsed"].max())

# ===== 3. Create additional time variables =====
df["year"] = df["month_parsed"].dt.year
df["month_num"] = df["month_parsed"].dt.month

# Create a YYYY-MM string variable
df["year_month"] = df["month_parsed"].dt.to_period("M").astype(str)

# ===== 4. Construct the dependent variables =====
# avg_players may be zero, so use log(avg_players + 1)
df["log_avg_players"] = np.log(df["avg_players"] + 1)

# Peak players can also be used as robustness check
df["log_peak_players"] = np.log(df["peak_players"] + 1)

# ===== 5. Set panel-like index =====
df = df.set_index(["steam_appid", "month_parsed"]).sort_index()

# ===== 6. Save the cleaned dataset =====
clean_path = "steam_panel_clean.csv"
df.reset_index().to_csv(clean_path, index=False)
print("Cleaned data saved to:", clean_path)
print("Cleaned data shape:", df.reset_index().shape)

!pip install chardet

import chardet
rawdata = open("Twitch_game_data.csv", "rb").read()
result = chardet.detect(rawdata)
result

import pandas as pd

try:
    twitch = pd.read_csv("Twitch_game_data.csv", encoding="MacRoman")
    print("Loaded successfully with MacRoman")
except Exception as e:
    print("MacRoman strict decode failed:", e)
    print("Trying MacRoman with ignore...")
    twitch = pd.read_csv("Twitch_game_data.csv", encoding="MacRoman", encoding_errors="ignore")

print("Shape:", twitch.shape)
print(twitch.head())

import pandas as pd
import numpy as np

# 1. Load cleaned Steam panel

steam = pd.read_csv("steam_panel_clean.csv")
print("Steam panel shape:", steam.shape)
print(steam.head())

# Keep essential columns from Steam
steam = steam[[
    "steam_appid", "name", "month_parsed", "month",
    "avg_players", "gain", "gain_percent", "peak_players",
    "year", "month_num", "year_month",
    "log_avg_players", "log_peak_players"
]]

# 2. Load Twitch game-level monthly dataset

twitch = pd.read_csv("Twitch_game_data.csv", encoding="MacRoman")
print("Raw Twitch shape:", twitch.shape)
print(twitch.head())

# 3. Clean Twitch columns

# Make column names lower case and replace spaces with underscores
twitch.columns = [c.strip().lower().replace(" ", "_") for c in twitch.columns]
print("Cleaned Twitch columns:", twitch.columns)

# Ensure 'month' is numeric
twitch["month"] = twitch["month"].astype(int)

# 4. Create year_month in Twitch for merging

# Zero-pad month (1 → "01")
twitch["month_padded"] = twitch["month"].astype(str).str.zfill(2)

# Construct YYYY-MM string
twitch["year_month"] = twitch["year"].astype(str) + "-" + twitch["month_padded"]

# 5. Create core Twitch exposure variable: log(avg_viewers + 1)
# Replace missing avg_viewers with 0
twitch["avg_viewers"] = twitch["avg_viewers"].fillna(0)

# Log-transform (add 1 to avoid log(0))
twitch["log_avg_viewers"] = np.log(twitch["avg_viewers"] + 1)

# 6. Standardize game names in both datasets

def clean_name(x):
    if isinstance(x, str):
        x = x.lower().strip()
        x = x.replace("®", "").replace("™", "")
        x = x.replace(":", "").replace("-", " ")
        x = x.replace("  ", " ")
        return x
    return x

steam["name_clean"] = steam["name"].apply(clean_name)
twitch["game_clean"] = twitch["game"].apply(clean_name)

# Quick check
print("Example Steam names:", steam["name_clean"].head())
print("Example Twitch names:", twitch["game_clean"].head())

# 7. Merge Steam × Twitch on (name_clean, year_month)

merged = steam.merge(
    twitch,
    left_on=["name_clean", "year_month"],
    right_on=["game_clean", "year_month"],
    how="left"   # keep all Steam observations; Twitch may be missing for some games
)

print("Merge completed. Shape:", merged.shape)
print("Merged columns:", merged.columns)

# 8. Create lagged Twitch exposure variable: log_avg_viewers at t-1

# Sort by game and time using the YYYY-MM string
merged = merged.sort_values(["steam_appid", "year_month"])

# Group by game (steam_appid) and shift log_avg_viewers by 1 month
merged["log_avg_viewers_lag1"] = merged.groupby("steam_appid")["log_avg_viewers"].shift(1)

# 9. Save final merged dataset

output_path = "steam_twitch_panel.csv"
merged.to_csv(output_path, index=False)

print("FINAL merged dataset saved to:", output_path)
print("Final shape:", merged.shape)
print(merged.head())

import pandas as pd
import numpy as np

# 1. Load final merged panel

df = pd.read_csv("steam_twitch_panel.csv")
print("Dataset loaded. Shape:", df.shape)

# Show first few rows
print(df.head())

# 2. Basic info

print("\n=== BASIC INFO ===")
print(df.info())

print("\n=== COLUMN NAMES ===")
print(df.columns.tolist())

# 3. Number of unique games + time periods

print("\n=== UNIQUE COUNTS ===")
print("Unique games:", df["steam_appid"].nunique())
print("Unique year_month values:", df["year_month"].nunique())

# 4. Time range summary

print("\n=== TIME RANGE ===")
print("Earliest month:", df["year_month"].min())
print("Latest month:", df["year_month"].max())

# 5. Observations per game (panel balance check)

obs_per_game = df.groupby("steam_appid").size()

print("\n=== PANEL STRUCTURE ===")
print("Mean months per game:", obs_per_game.mean())
print("Median months per game:", obs_per_game.median())
print("Min months per game:", obs_per_game.min())
print("Max months per game:", obs_per_game.max())

# Optional: quick distribution
print("\nObservations per game distribution summary:")
print(obs_per_game.describe())

# 6. Summary statistics for key variables

key_vars = [
    "avg_players", "log_avg_players",
    "avg_viewers", "log_avg_viewers",
    "log_avg_viewers_lag1"
]

print("\n=== SUMMARY STATISTICS ===")
print(df[key_vars].describe(percentiles=[0.01, 0.25, 0.5, 0.75, 0.99]))

# 7. Missing values report

print("\n=== MISSING VALUES ===")
print(df[key_vars].isna().sum())

# 8. Correlation matrix

print("\n=== CORRELATION MATRIX ===")
print(df[key_vars].corr())

# 9. Yearly counts

df["year"] = df["year_month"].str[:4].astype(int)

print("\n=== OBS COUNT PER YEAR ===")
print(df.groupby("year").size())

# 10. Top 20 games by number of observations

print("\n=== TOP 20 GAMES BY MONTH COUNT ===")
top_games = (
    df.groupby(["steam_appid", "name_clean"])
    .size()
    .sort_values(ascending=False)
    .head(20)
)
print(top_games)

# Extract matched sample where Twitch exposure exists
reg = merged.dropna(subset=["log_avg_viewers_lag1"])

print("Regression sample shape:", reg.shape)
print(reg.head())

# Save regression sample
reg.to_csv("regression_sample.csv", index=False)
print("Saved regression sample to regression_sample.csv")

!pip install missingno

import pandas as pd
import missingno as msno
import matplotlib.pyplot as plt

# Load regression sample
df = pd.read_csv("regression_sample.csv")

# Show missing value heatmap
plt.figure(figsize=(12,6))
msno.matrix(df)
plt.title("Missing Value Map for Regression Sample")
plt.show()

controls = ["peak_players", "gain_percent"]

!pip install linearmodels

import pandas as pd
import numpy as np
import statsmodels.api as sm
from linearmodels.panel import PanelOLS

# 1. Load regression sample

df = pd.read_csv("regression_sample.csv")
print("Raw regression sample shape:", df.shape)

# Convert year_month to datetime
df["year_month_dt"] = pd.to_datetime(df["year_month"])

# Choose controls
controls = ["peak_players", "gain_percent"]

# Keep only the variables we need
reg = df[[
    "steam_appid", "year_month", "year_month_dt",
    "log_avg_players", "log_avg_viewers_lag1"
] + controls].copy()

# Drop any rows with missing key variables
reg = reg.dropna(subset=["log_avg_players", "log_avg_viewers_lag1"])
print("After dropping missing key vars:", reg.shape)

# 2. MODEL 1: y ~ x  (no controls, no FE) - OLS with clustered SE

X1 = sm.add_constant(reg["log_avg_viewers_lag1"])
model1 = sm.OLS(reg["log_avg_players"], X1)
results1 = model1.fit(cov_type="cluster", cov_kwds={"groups": reg["steam_appid"]})

print("\n=== MODEL 1: y on x (OLS, clustered by game) ===\n")
print(results1.summary())

# 3. MODEL 2: y ~ x + controls  (no FE) - OLS with clustered SE

X2 = sm.add_constant(reg[["log_avg_viewers_lag1"] + controls])
model2 = sm.OLS(reg["log_avg_players"], X2)
results2 = model2.fit(cov_type="cluster", cov_kwds={"groups": reg["steam_appid"]})

print("\n=== MODEL 2: y on x + controls (OLS, clustered by game) ===\n")
print(results2.summary())

# 4. Prepare panel data for FE models (M3, M4)

panel = reg.set_index(["steam_appid", "year_month_dt"]).sort_index()

y = panel["log_avg_players"]
X_fe = panel[["log_avg_viewers_lag1"] + controls]

# 5. MODEL 3: y ~ x + controls + game FE

model3 = PanelOLS(
    y,
    X_fe,
    entity_effects=True,   # game fixed effects
    time_effects=False
)

results3 = model3.fit(cov_type="clustered", cluster_entity=True)

print("\n=== MODEL 3: y on x + controls + game FE ===\n")
print(results3.summary)

# 6. MODEL 4: y ~ x + controls + game FE + time FE

model4 = PanelOLS(
    y,
    X_fe,
    entity_effects=True,   # game fixed effects
    time_effects=True      # time fixed effects
)

results4 = model4.fit(cov_type="clustered", cluster_entity=True)

print("\n=== MODEL 4: y on x + controls + game FE + time FE ===\n")
print(results4.summary)

import pandas as pd
import matplotlib.pyplot as plt

# Load regression sample
df = pd.read_csv("regression_sample.csv")

# Convert time column
df["year_month_dt"] = pd.to_datetime(df["year_month"])

# 1) Scatter plot: Twitch vs Steam

plt.figure(figsize=(8,6))
plt.scatter(df["log_avg_viewers_lag1"], df["log_avg_players"], alpha=0.3)
plt.xlabel("Log Avg Twitch Viewers (lag1)")
plt.ylabel("Log Avg Steam Players")
plt.title("Scatter: Twitch Exposure vs Steam Demand")
plt.show()

# 2) Time series: choose a game (Counter-Strike: appid 10)

cs = df[df["steam_appid"] == 10].sort_values("year_month_dt")

plt.figure(figsize=(10,6))
plt.plot(cs["year_month_dt"], cs["log_avg_players"], label="Log Steam Players")
plt.plot(cs["year_month_dt"], cs["log_avg_viewers_lag1"], label="Log Twitch Viewers (lag1)")
plt.xlabel("Time")
plt.ylabel("Log Values")
plt.title("Time Series: Counter-Strike (Steam vs Twitch)")
plt.legend()
plt.show()

import pandas as pd
import statsmodels.api as sm
from linearmodels.panel import PanelOLS

# Load regression sample (already matched Steam–Twitch panel)
df = pd.read_csv("regression_sample.csv")

# Convert time to datetime
df["year_month_dt"] = pd.to_datetime(df["year_month"])

# Sort for lag construction
df = df.sort_values(["steam_appid", "year_month_dt"])

# Construct lagged players and lagged viewers if needed
df["log_avg_players_lag1"] = df.groupby("steam_appid")["log_avg_players"].shift(1)
# You already have log_avg_viewers_lag1, but if not:
# df["log_avg_viewers_lag1"] = df.groupby("steam_appid")["log_avg_viewers"].shift(1)

# Drop rows with missing key variables for each test separately later
print(df[["log_avg_players", "log_avg_players_lag1", "log_avg_viewers", "log_avg_viewers_lag1"]].head())

# Keep rows where we have both players_t and viewers_t
df_contemp = df.dropna(subset=["log_avg_players", "log_avg_viewers"])

# Panel index
panel_contemp = df_contemp.set_index(["steam_appid", "year_month_dt"])

y_c = panel_contemp["log_avg_players"]
X_c = panel_contemp[["log_avg_viewers"]]  # contemporaneous viewers

model_c = PanelOLS(
    y_c,
    X_c,
    entity_effects=True,
    time_effects=True
)
res_c = model_c.fit(cov_type="clustered", cluster_entity=True)

print("\n=== Test 1A: log_players_t ~ log_viewers_t (contemporaneous, FE) ===\n")
print(res_c.summary)

# Keep rows where we have players_t and viewers_{t-1}
df_lag = df.dropna(subset=["log_avg_players", "log_avg_viewers_lag1"])

panel_lag = df_lag.set_index(["steam_appid", "year_month_dt"])

y_l = panel_lag["log_avg_players"]
X_l = panel_lag[["log_avg_viewers_lag1"]]  # lagged viewers

model_l = PanelOLS(
    y_l,
    X_l,
    entity_effects=True,
    time_effects=True
)
res_l = model_l.fit(cov_type="clustered", cluster_entity=True)

print("\n=== Test 1B: log_players_t ~ log_viewers_{t-1} (lagged, FE) ===\n")
print(res_l.summary)

# Keep rows where we have viewers_t and lagged players
df_rev = df.dropna(subset=["log_avg_viewers", "log_avg_players_lag1"])

panel_rev = df_rev.set_index(["steam_appid", "year_month_dt"])

y_rev = panel_rev["log_avg_viewers"]               # viewers_t
X_rev = panel_rev[["log_avg_players_lag1"]]        # players_{t-1}

model_rev = PanelOLS(
    y_rev,
    X_rev,
    entity_effects=True,
    time_effects=True
)
res_rev = model_rev.fit(cov_type="clustered", cluster_entity=True)

print("\n=== Test 2: log_viewers_t ~ log_players_{t-1} (reverse causality test, FE) ===\n")
print(res_rev.summary)

import pandas as pd

df = pd.read_csv("regression_sample.csv")

# Columns to drop
drop_cols = [
    "avg_players",
    "avg_viewers",
    "avg_channels",
    "avg_viewer_ratio",
    "hours_watched",
    "hours_streamed",
    "streamers",
    "peak_players",
    "peak_viewers",
    "peak_channels",
]

# Only drop columns that exist
drop_cols = [c for c in drop_cols if c in df.columns]

df_clean = df.drop(columns=drop_cols)

df_clean.to_csv("regression_sample_clean.csv", index=False)

df_clean.head()

!pip install pytrends --quiet

import pandas as pd
from pytrends.request import TrendReq
import time

# 1. Load your cleaned regression sample
reg_df = pd.read_csv("regression_sample_clean.csv")

print("Regression sample shape:", reg_df.shape)
print(reg_df[["steam_appid", "name_clean"]].head())

# 2. Build game list from Steam game names
#    You can also use "game_clean" if you prefer the Twitch names.
game_counts = reg_df["name_clean"].value_counts()
print("\nNumber of unique games:", game_counts.shape[0])
game_counts.head(20)

TOP_N = None

if TOP_N is None:
    games = game_counts.index.tolist()
else:
    games = game_counts.index[:TOP_N].tolist()

print("Number of games to download trends for:", len(games))
print("Sample games:", games[:10])

# Initialize Google Trends connection
pytrends = TrendReq(hl='en-US', tz=360)

def fetch_trend_for_game(game_name,
                         start_date="2012-01-01",
                         end_date="2025-01-01",
                         sleep_sec=6):
    """
    Fetch monthly Google Trends index for a single game.
    Returns a DataFrame with columns: ['date', 'game_clean', 'google_trend'].
    """
    # Use the game name as search keyword; lower() can sometimes help matching
    kw = game_name.lower()

    # Build payload for this keyword
    timeframe = f"{start_date} {end_date}"
    pytrends.build_payload([kw], timeframe=timeframe, geo="")

    # Query interest over time
    df = pytrends.interest_over_time()

    # If no data returned, skip
    if df.empty:
        print(f"[NO DATA] {game_name}")
        time.sleep(sleep_sec)
        return None

    # Reset index so 'date' becomes a normal column
    df = df.reset_index()

    # Keep only date and the keyword column
    df = df[["date", kw]]

    # Rename the trend column to a generic name
    df = df.rename(columns={kw: "google_trend"})

    # Add game identifier
    df["game_clean"] = game_name

    print(f"[OK] {game_name} — {df.shape[0]} rows")

    # Be kind to Google and sleep a bit
    time.sleep(sleep_sec)

    return df

all_trends = []

for i, g in enumerate(games, start=1):
    try:
        print(f"{i}/{len(games)} Fetching trends for: {g}")
        tmp = fetch_trend_for_game(g)
        if tmp is not None:
            all_trends.append(tmp)
    except Exception as e:
        print(f"[ERROR] {g}: {e}")
        # In case of error, wait a bit longer
        time.sleep(15)

# Concatenate all results
if len(all_trends) > 0:
    gt_df = pd.concat(all_trends, ignore_index=True)
else:
    gt_df = pd.DataFrame(columns=["date", "game_clean", "google_trend"])

print("\nFinal Google Trends panel shape:", gt_df.shape)
gt_df.head()

gt_df.to_csv("google_trends_panel_long.csv", index=False)
print("Saved google_trends_panel_long.csv")

import pandas as pd

gt = pd.read_csv("google_trends_panel_long.csv")
print(gt.columns)

import pandas as pd

# 1. Load your regression panel
reg = pd.read_csv("regression_sample_clean.csv")
print("Regression sample shape:", reg.shape)
print("Regression columns:", reg.columns.tolist())

# 2. Load Google Trends panel (615 games)
gt = pd.read_csv("google_trends_panel_long.csv")
print("Google Trends shape:", gt.shape)
print("Google Trends columns:", gt.columns.tolist())

# Create a proper date column in reg
if "date" in reg.columns:
    reg["date"] = pd.to_datetime(reg["date"])
elif "month_parsed" in reg.columns:
    # Example: '2016-07-01'
    reg["date"] = pd.to_datetime(reg["month_parsed"])
elif "year_month" in reg.columns:
    # Example: '2016-07' -> '2016-07-01'
    reg["date"] = pd.to_datetime(reg["year_month"].astype(str) + "-01")
else:
    raise ValueError(
        "Could not find a date-like column in regression_sample_clean.csv. "
        "Available columns: " + ", ".join(reg.columns)
    )

# Standardize game name column
if "game_clean" not in reg.columns:
    raise ValueError("regression_sample_clean.csv must contain 'game_clean'.")

reg["game_clean"] = reg["game_clean"].str.lower().str.strip()

# Google Trends date + game_clean
gt["date"] = pd.to_datetime(gt["date"])
gt["game_clean"] = gt["game_clean"].str.lower().str.strip()

# Merge Google Trends (left join to keep your regression sample)
reg_trend = reg.merge(
    gt,
    on=["game_clean", "date"],
    how="left"
)

print("Merged shape:", reg_trend.shape)
print(reg_trend[["game_clean", "date", "google_trend"]].head())

# Check coverage of Google Trends in your regression sample
missing_ratio = reg_trend["google_trend"].isna().mean()
print(f"Share of missing google_trend in regression sample: {missing_ratio:.3f}")

# Sort by game and date so lags are well-defined
reg_trend = reg_trend.sort_values(["game_clean", "date"])

# Lag of viewers and players (if not already created)
if "log_avg_viewers_lag1" not in reg_trend.columns:
    reg_trend["log_avg_viewers_lag1"] = (
        reg_trend.groupby("game_clean")["log_avg_viewers"].shift(1)
    )

if "log_avg_players_lag1" not in reg_trend.columns:
    reg_trend["log_avg_players_lag1"] = (
        reg_trend.groupby("game_clean")["log_avg_players"].shift(1)
    )

# Lag of Google Trends (this will be your main IV candidate)
reg_trend["google_trend_lag1"] = (
    reg_trend.groupby("game_clean")["google_trend"].shift(1)
)

print(reg_trend[["game_clean", "date", "log_avg_viewers",
                 "log_avg_viewers_lag1", "google_trend_lag1"]].head())

# Keep only rows where all key variables exist
iv_vars = ["log_avg_players", "log_avg_viewers",
           "google_trend_lag1"]

iv_df = reg_trend.dropna(subset=iv_vars).copy()
print("IV sample shape:", iv_df.shape)
iv_df[["game_clean", "date", "log_avg_players",
       "log_avg_viewers", "google_trend_lag1"]].head()

import pandas as pd
import numpy as np

# Load regression sample
reg = pd.read_csv("regression_sample_clean.csv")

# Ensure date exists and convert to datetime
if "date" not in reg.columns:
    if "month_parsed" in reg.columns:
        reg["date"] = pd.to_datetime(reg["month_parsed"])
    else:
        raise ValueError("No date or month_parsed column found in regression_sample_clean.csv")

# Load Google Trends data
gt = pd.read_csv("google_trends_panel_long.csv")
gt["date"] = pd.to_datetime(gt["date"])

# Merge on game_clean + date
merged = reg.merge(
    gt,
    on=["game_clean", "date"],
    how="left"
)

print("Shape after merging Google Trends:", merged.shape)

# Sort before generating lag
merged = merged.sort_values(["game_clean", "date"])

# Create lag: google_trend_lag1
merged["google_trend_lag1"] = merged.groupby("game_clean")["google_trend"].shift(1)

print("Missing google_trend_lag1:", merged["google_trend_lag1"].isna().sum())

# Save final dataset
merged.to_csv("final_regression_with_google_trends.csv", index=False)

print("Saved final dataset: final_regression_with_google_trends.csv")
print("Final columns:", merged.columns.tolist())

# Imports
import pandas as pd
import numpy as np

import statsmodels.api as sm
import statsmodels.formula.api as smf
from linearmodels.iv import IV2SLS

import matplotlib.pyplot as plt

# Make plots a bit bigger by default
plt.rcParams["figure.figsize"] = (10, 5)


# 1. Load final regression dataset (Steam + Twitch + Google Trends)
# This file should already contain:
# - Steam variables (log_avg_players, log_peak_players, gain_percent, etc.)
# - Twitch variables (log_avg_viewers, game_clean, etc.)
# - Google Trends variables (google_trend, google_trend_lag1)
df = pd.read_csv("final_regression_with_google_trends.csv")
print("Raw final dataset shape:", df.shape)
print(df.head(3))


# 2. Basic cleaning and construction of IV sample

# Ensure date is in datetime format; if missing, construct from year_x and month_num
if "date" in df.columns:
    try:
        df["date"] = pd.to_datetime(df["date"])
    except Exception:
        # Fallback: if date is string-like 'YYYY-MM'
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
elif ("year_x" in df.columns) and ("month_num" in df.columns):
    df["date"] = pd.to_datetime(
        df["year_x"].astype(int).astype(str) + "-" +
        df["month_num"].astype(int).astype(str) + "-01"
    )
else:
    raise ValueError("No usable date information found to construct time index.")

# Create a string version of date for fixed effects (C(date_str) in formulas)
df["date_str"] = df["date"].dt.to_period("M").astype(str)

# Drop rows with missing key variables for IV estimation
key_vars = ["log_avg_players", "log_avg_viewers", "google_trend_lag1"]
df_reg = df.dropna(subset=key_vars).copy()

print("\nIV regression sample shape:", df_reg.shape)
print("Unique games in IV sample:", df_reg["game_clean"].nunique())
print("Unique months in IV sample:", df_reg["date_str"].nunique())


# 3. Summary statistics
summary_cols = [
    "log_avg_players",
    "log_avg_viewers",
    "log_peak_players",
    "gain_percent",
    "google_trend",
    "google_trend_lag1",
]

print("\n=== SUMMARY STATISTICS (IV sample) ===")
summary_table = df_reg[summary_cols].describe().T
print(summary_table)

# Optionally export summary stats table to CSV (for paper/appendix)
summary_table.to_csv("summary_stats_iv_sample.csv")
print("\nSaved summary stats to summary_stats_iv_sample.csv")


# 4. Baseline OLS with game and time fixed effects
# Dependent variable: log_avg_players
# Main regressor: log_avg_viewers (endogenous)
# Fixed effects: game_clean (game FE) and date_str (time FE)
ols_formula = "log_avg_players ~ log_avg_viewers + C(game_clean) + C(date_str)"

ols_model = smf.ols(
    ols_formula,
    data=df_reg
).fit(cov_type="cluster", cov_kwds={"groups": df_reg["game_clean"]})

print("\n=== BASELINE OLS: log_avg_players on log_avg_viewers (with FE, clustered by game) ===\n")
print(ols_model.summary())


# 5. First Stage (FSLS): log_avg_viewers ~ google_trend_lag1 + FE
# This is the first stage of the IV model.

fs_formula = "log_avg_viewers ~ google_trend_lag1 + C(game_clean) + C(date_str)"

fs_model = smf.ols(
    fs_formula,
    data=df_reg
).fit(cov_type="cluster", cov_kwds={"groups": df_reg["game_clean"]})

print("\n=== FIRST STAGE (FSLS): log_avg_viewers on google_trend_lag1 + FE ===\n")
print(fs_model.summary())



# 6. IV-2SLS main specification (TSLS)
# Second Stage:
# log_avg_players = alpha_i + gamma_t + beta * log_avg_viewers_hat + error
# where log_avg_viewers_hat is predicted from the first stage.
# FE: game_clean and date_str
iv_formula = "log_avg_players ~ 1 + [log_avg_viewers ~ google_trend_lag1] + C(game_clean) + C(date_str)"

iv_model = IV2SLS.from_formula(
    iv_formula,
    data=df_reg
).fit(cov_type="clustered", clusters=df_reg["game_clean"])

print("\n=== IV-2SLS RESULTS: log_avg_players on instrumented log_avg_viewers (with FE) ===\n")
print(iv_model.summary)

# - coefficient on log_avg_viewers (should be ~ 1.0)
# - standard error, t-stat, confidence interval


# 7. Reverse IV (for discussion, not main specification)
# swap the dependent and endogenous variables:
# log_avg_viewers = alpha_i + gamma_t + theta * log_avg_players_hat + error
# This is used to check whether we find evidence that players drive viewership.
reverse_iv_formula = "log_avg_viewers ~ 1 + [log_avg_players ~ google_trend_lag1] + C(game_clean) + C(date_str)"

reverse_iv_model = IV2SLS.from_formula(
    reverse_iv_formula,
    data=df_reg
).fit(cov_type="clustered", clusters=df_reg["game_clean"])

print("\n=== REVERSE IV RESULTS: log_avg_viewers on instrumented log_avg_players (with FE) ===\n")
print(reverse_iv_model.summary)


# 8. Time series plots: Google Trends vs Twitch vs Steam
# Simple visualization for a few representative games.
# This is mainly to show co-movement of search interest, viewership, and players over time.

sample_games = [
    "counter strike",
    "pubg battlegrounds",
    "rust"
]

for g in sample_games:
    temp = df_reg[df_reg["game_clean"] == g].sort_values("date")
    if temp.empty:
        continue

    plt.figure(figsize=(12, 5))
    plt.plot(temp["date"], temp["google_trend"], label="Google Trends index")
    plt.plot(temp["date"], temp["log_avg_viewers"], label="Twitch viewers (log)")
    plt.plot(temp["date"], temp["log_avg_players"], label="Steam players (log)")
    plt.title(f"Time series: {g}")
    plt.xlabel("Month")
    plt.ylabel("Level / log")
    plt.xticks(rotation=45)
    plt.legend()
    plt.tight_layout()
    plt.show()